name: automation tests

on:
  workflow_dispatch:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  automation-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set version from git commit SHA
        run: mvn -B -ntp versions:set -DgenerateBackupPoms=false -DnewVersion="${GITHUB_SHA::7}"

      - name: Build jar file
        run: mvn -B -ntp package

      - name: Run automation tests
        run: mvn -B -ntp verify -P automation-tests -D slack.token=${CI_SLACK_TOKEN} -D slack.channel=automation-tests -D selenide.headless=true