name: main
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install -DskipTests -DskipTests
      
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: keycloak-extension
          path: target/*.jar  # Adjust this path based on where your JAR is generated
